# Generated by Django 3.1.2 on 2020-10-18 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coches_Vendidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('precio', models.IntegerField()),
                ('extras_instalados', models.CharField(max_length=20)),
                ('numero_puertas', models.IntegerField()),
                ('codigo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Revisiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cambio_aceite', models.CharField(max_length=2)),
                ('cambio_filtro', models.CharField(max_length=2)),
                ('revision_frenos', models.CharField(max_length=2)),
                ('otros', models.CharField(max_length=255)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coches.coches_vendidos')),
            ],
        ),
    ]
